name: deploy ⬆️

on: workflow_dispatch

jobs:

  build:
    name: Build ⚒️
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/path
          docker compose down
          git stash -u
          git pull
          docker compose up -d --build
